name: Publish

on:
  pull_request:
    branches:
      - master
    types: [closed]

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  publish_and_deploy:
    name: Publish 📦 & Deploy 🚀 
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node 🔧
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: 'https://npm.pkg.github.com'
          scope: '@dcolesdev'
      - name: Setup GitHub Actions Bot 🤖
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Install 🔻
        run: yarn ci:install
      - name: Build 👷
        run: yarn ci:build
      - name: Publish Packages 📦
        run: yarn ci:publish
      - name: Update Docs 📜
        run: |
          yarn ci:docs
          git commit -am "chore(docs) version update"
          git push
